name: Publish documentation
on:
  push:
    branches:
      - documentation
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: ~/.cache/pip
      - run: pip install --upgrade mkdocs-material
      - run: mkdocs gh-deploy --force