name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-and-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set root
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run unit tests
      run: |
        pytest unit_tests

    - name: Run validation tests for input file
      run: |
        if [ -f validation_tests/test_input_file.py ]; then pytest validation_tests/test_input_file.py
        else echo "Input file does not exist. Skipping tests."; fi

    - name: Run validation tests for output file
      run: |
        if [ -f validation_tests/test_output_file.py ]; then pytest validation_tests/test_output_file.py
        else echo "Output file does not exist. Skipping tests."; fi

    - name: Linting with Super-Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_PYTHON_PYLINT: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}